### ISSUE TITLE
5.1.1.2 WMO messages

### ISSUE THREAD

**Issue by isedwards** [opencdms-project/project-technical-team#162]
This component allows for the import of data from a range of WMO message formats, including TAC and TDCF.

As both historical and current data will need to be imported, this component should be able to work with data in a wide variety of past, present (and future) data formats.

Some examples are:
1. Binary:
    1. BUFR
    2. GRIB
2. Alphanumeric:
    1. CREX
    2.  SYNOP
    3.  TEMP
    4.  SHIP
    5.  METAR
    6.  World Weather Records

Note: While TAC formats are being phased out, support for them will still be required by this component to support the ingest of historical data.

For more information, see:
a) WMO international codes

**Comment by isedwards** [comment]
Notes:
- WMO CF-NetCDF is now a message format

**Comment by isedwards** [comment]
- [ ] Identify which formats will be supported (PAT / ET-DRC)
- [ ] Which project (opencdms/wis2box) is doing the development of each (Dave)
- [ ] Ensue issues are raised as appropriate (in correct repo)
- [ ] Add acceptance criteria
