### ISSUE TITLE
9.1.1.2 Identity and access management

### ISSUE THREAD

**Issue by isedwards** [opencdms-project/project-technical-team#235]
This component supports policies and functionalities that enable granular user access to the organization’s IT resources and data.

**Comment by david-i-berry** [comment]
- [ ] Select backend framework for authentication (expected to be Flask).
- [ ] Use JWT tokens with selected framework and UI.
- [ ] Role based access control (RBAC), roles TBD. Implemented in ClimSOFT version.

**Comment by david-i-berry** [comment]
@david-i-berry Link to WIS2box authentication to be added here.

**Comment by isedwards** [comment]
SURFACE ROLES
- Climate Administrator
- Climate Officer
- Data Entry Clerk
- Guest
- Instrument Technician
- Meteorologist
- System Administrator

Climsoft default roles in dictionary format
- https://github.com/climsoft/climsoft-api/blob/main/src/climsoft_api/middlewares/rbac_config.py
